# This is a basic workflow to help you get started with Actions

name: CI

env:
  REGISTRY: quay.io/${{ secrets.REGISTRY_NAMESPACE }}/
  REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  IMAGE_NAME: ${{ REGISTRY }}my-wildfly-app'

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ buildpack ]
  pull_request:
    branches: [ buildpack ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build image
        uses: bigloupe/buildpacks-action@master
        with:
          image: ${{ env.IMAGE_NAME }}
          path: '.'
          builder: 'quay.io/jmesnil/wildfly-builder'
      - name: Docker Login to Quay.io
        uses: docker/login-action@v1.9.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
      - name: Push Images To Registry
        run: |-
         docker push ${{ env.IMAGE_NAME }}
